package pl.adamsiedlecki.obm.mongo.document;

public enum MessageTypeEnum {

    TEMPERATURE_REQUEST,
    TEMPERATURE_RESPONSE,

    HUMIDITY_REQUEST,
    HUMIDITY_RESPONSE,

    VOLTAGE_REQUEST,
    VOLTAGE_RESPONSE,

    GATE_OPENED,
    GATE_CLOSED,

    DEVICE_ON_REQUEST,
    DEVICE_ON_RESPONSE,

    DEVICE_OFF_REQUEST,
    DEVICE_OFF_RESPONSE,

    UNKNOWN
}
